name: rgrg_env
channels:
  - pytorch
  - conda-forge
  - defaults
  - pkgs/main
dependencies:
  - python=3.9.13
  - pip=22.2.2
  - pillow=11.0.0
  - spacy-model-en_core_web_trf
  - pip:
    - -e .
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.10
    - aiosignal==1.3.1
    - albumentations==1.4.3
    - altair==5.5.0
    - async-timeout==5.0.1
    - attrs==24.2.0
    - bert-score==0.3.13
    - blinker==1.9.0
    - spacy-transformers==1.2.5
    - blis==0.7.11
    - cachetools==5.5.0
    - catalogue==2.0.10
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - cloudpathlib==0.16.0
    - colorama==0.4.6
    - confection==0.1.5
    - contourpy==1.3.1
    - cymem==2.0.10
    - datasets==3.1.0
    - dill==0.3.8
    - en-core-web-trf==3.4.0
    - evaluate==0.4.3
    - filelock==3.16.1
    - fonttools==4.55.2
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - gitdb==4.0.11
    - GitPython==3.1.43
    - grpcio==1.68.1
    - huggingface-hub==0.26.5
    - idna==3.10
    - imageio==2.36.1
    - Jinja2==3.1.4
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kiwisolver==1.4.7
    - langcodes==3.5.0
    - language_data==1.3.0
    - lazy_loader==0.4
    - lightning-utilities==0.11.9
    - marisa-trie==1.2.1
    - Markdown==3.7
    - markdown-it-py==3.0.0
    - MarkupSafe==3.0.2
    - matplotlib==3.9.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - murmurhash==1.0.11
    - narwhals==1.17.0
    - networkx==3.4.2
    - nltk==3.9.1
    - numpy==1.26.4
    - opencv-python-headless==4.10.0.84
    - packaging==24.2
    - pandas==2.2.3
    - pathlib_abc==0.1.1
    - pathy==0.11.0
    - patsy==1.0.1
    - preshed==3.0.9
    - propcache==0.2.1
    - protobuf==5.29.1
    - pyarrow==18.1.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.8
    - pydantic==1.10.9
    - pydeck==0.9.1
    - Pygments==2.18.0
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - PyYAML==6.0.2
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - rich==13.9.4
    - rpds-py==0.22.3
    - scikit-image==0.24.0
    - scikit-learn==1.6.0
    - scipy==1.14.1
    - six==1.17.0
    - smart-open==6.4.0
    - smmap==5.0.1
    - spacy==3.5.2
    - spacy-alignments==0.9.1
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.5.0
    - statsmodels==0.14.4
    - streamlit==1.41.0
    - sympy==1.13.1
    - tenacity==9.0.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - thinc==8.1.12
    - threadpoolctl==3.5.0
    - tifffile==2024.9.20
    - tokenizers==0.12.1
    - toml==0.10.2
    - torch==2.5.1
    - torchinfo==1.8.0
    - torchmetrics==1.6.0
    - torchvision==0.20.1
    - tornado==6.4.2
    - tqdm==4.67.1
    - transformers==4.19.2
    - typer==0.7.0
    - typing_extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.3
    - wasabi==0.10.1
    - watchdog==6.0.0
    - weasel==0.3.4
    - Werkzeug==3.1.3
    - xxhash==3.5.0
    - yarl==1.18.3
    - gdown
